# Generated by Django 2.2.4 on 2019-11-29 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavaricle',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='收藏时间'),
        ),
        migrations.AddField(
            model_name='userreadaricle',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='浏览时间'),
        ),
    ]
