# Generated by Django 2.2.4 on 2019-11-29 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0002_auto_20191129_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavaricle',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='收藏时间'),
        ),
        migrations.AlterField(
            model_name='userreadaricle',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='浏览时间'),
        ),
    ]
