# Generated by Django 2.2.4 on 2019-11-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0004_userreadaricle_articlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavaricle',
            name='articlename',
            field=models.CharField(default='', help_text='题目', max_length=50, null=True, verbose_name='题目'),
        ),
    ]
