# Generated by Django 2.2.4 on 2019-11-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0005_userfavaricle_articlename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavaricle',
            old_name='articlename',
            new_name='articleName',
        ),
        migrations.RenameField(
            model_name='userreadaricle',
            old_name='articlename',
            new_name='articleName',
        ),
    ]
