# Generated by Django 2.2.4 on 2019-11-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operations', '0008_comment_articlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userName',
            field=models.CharField(default='弟弟', max_length=30, verbose_name='用户昵称'),
            preserve_default=False,
        ),
    ]
