# Generated by Django 2.2.4 on 2019-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20191125_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='typ',
            field=models.CharField(choices=[('sqz', '湿气重'), ('poor_sleep', '睡眠质量差'), ('low_dkl', '抵抗力低下'), ('little_hair', '脱发')], default='', max_length=20, null=True, verbose_name='种类'),
        ),
    ]
