# Generated by Django 2.2.4 on 2019-11-25 12:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191125_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='click_num',
            field=models.IntegerField(default=0, null=True, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=0, null=True, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(max_length=500, null=True, verbose_name='商品简短描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=0, null=True, verbose_name='库存数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_sn',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='商品唯一货号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False, null=True, verbose_name='是否热销'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_new',
            field=models.BooleanField(default=False, null=True, verbose_name='是否新品'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='market_price',
            field=models.FloatField(default=0, null=True, verbose_name='市场价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ship_free',
            field=models.BooleanField(default=True, null=True, verbose_name='是否承担运费'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shop_price',
            field=models.FloatField(default=0, null=True, verbose_name='本店价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sold_num',
            field=models.IntegerField(default=0, null=True, verbose_name='商品销售量'),
        ),
    ]
