# Generated by Django 2.2.4 on 2019-11-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191124_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='typ',
            field=models.CharField(choices=[('sqz', '湿气重'), ('poor_sleep', '睡眠质量差'), ('low_dkl', '抵抗力低下'), ('little_hair', '脱发')], default='little_hair', max_length=20, verbose_name='种类'),
        ),
    ]
