# Generated by Django 2.2.4 on 2019-11-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191124_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='mobile',
        ),
    ]
