# Generated by Django 2.2.4 on 2019-11-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191128_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='typ',
            field=models.CharField(max_length=500, verbose_name='病症'),
        ),
    ]
