# Generated by Django 2.2.4 on 2019-12-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191129_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tag',
            field=models.TextField(default='', help_text='user标签', null=True, verbose_name='user标签'),
        ),
    ]
